name: Aparat GUI Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y \
        ffmpeg \
        xvfb \
        xdotool \
        firefox \
        x11-apps

    - name: Start virtual display
      run: |
        Xvfb :99 -screen 0 1280x720x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        sleep 3

    - name: Make scripts executable
      run: |
        chmod +x program.sh
        chmod +x control.sh
        chmod +x stream.sh
        chmod +x wr.sh
    - name: Start WR
      run: |
        ./wr.sh &
        sleep 5
    - name: Start program
      run: |
        ./program.sh &
        sleep 5

    - name: Start control loop
      run: |
        ./control.sh &
        sleep 2

    - name: Start streaming
      run: |
        ./stream.sh
